### ISSUE TITLE
IHM02A1 RED is always on

### ISSUE THREAD

**Issue by dexter-qjq** [stm32duino/X-NUCLEO-IHM02A1#10]
when i using a MCU contect to the IHM02A1 the Red Led is always on. I think there is maybe a fail condition, but i do not know how to fix this problem.

The status return value is 7c03 at the very beginning, after reseting device, the status retval is 7e03.. i think maybe the fail condition is caused by OCD, so i have disable the overcurrent dection in CONFIG, and set the OCD_TH to be 0x0f, but it dose not work.

P.S. i can GetParam and SetParam correctly, and Run and Move. But when moving, the ABS_POS register value is always is zero. Although the STEP_MODE register value has been changed, it does not change during running.

by the way, i connected the IHM02A1 to MCU as follow. IOREF(CN6), NRST(CN6), +5V(CN6), VIN(CN6), AVDD(CN5) -----5v +3.3V (CN6)----- 3.3V nCS(CN8), SDO(CN5), SDI(CN5),sck(CN9) ----- SPI interface nRST(CN9) ----- a GPIO all ground pins ----- GNDs, VS -------------24V

Thanks in advance.

**Comment by fpistm** [comment]
Hi @dexter-qjq,
sorry missed this issue.
@cparata have you an idea on this?

**Comment by dexter-qjq** [comment]
I tried the stepclock mode and provide the 40K HZ control pulse, however the motor moves even slower than speed 0x09900 in command mode with the same microsteps? how about this question? Thanks for your attention.

At 2019-09-13 21:59:42, "Frederic Pillon" <notifications@github.com> wrote:


Hi @dexter-qjq,
sorry missed this issue.
@cparata have you an idea on this?

**Comment by cparata** [comment]
Hi @dexter-qjq ,
which MCU are you using? Did you check that in your setup the SPI signals are well connected to the motor shield?
Best Regards,
Carlo

**Comment by dexter-qjq** [comment]
thanks. i have solved this problem.


 
I tried the stepclock mode and provide the 40K HZ control pulse, however the motor moves even slower than speed 0x09900 in command mode with the same microsteps? how about this question? Thanks for your attention.



On 09/16/2019 20:34, Carlo Parata wrote:

Hi @dexter-qjq ,
which MCU are you using? Did you check that in your setup the SPI signals are well connected to the motor shield?
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @dexter-qjq ,
unfortunately, I'm not expert of this mode for motor driver. Maybe at this link:

https://community.st.com/s/question/0D50X00009XkXBdSAN/how-do-we-use-stepclock-mode-when-operating-in-voltage-mode

you can find more information to fix your issue.
Best Regards,
Carlo

**Comment by fpistm** [comment]
> thanks. i have solved this problem.

Fine, so the original issue can be closed.
For the extra questions, it has been answered by @cparata.
And for support ST community is the best bet to get answer, here it is for issue related to the library not for support.

**Comment by FraGiura** [comment]
@dexter-qjq
> thanks. i have solved this problem.

I'm facing the same problem( IHM02A1 the Red Led is always on), 
Could you suggest me how to solve the problem?
Thanks in advance,
Francesco

**Comment by cparata** [comment]
Hi @FraGiura ,
which is the MCU board that you are using together with IHM02A1 shield?
Best Regards,
Carlo

**Comment by FraGiura** [comment]
Hi @cparata,

really thanks for the reply. 

I've connected a IHM02A1 expansion on a Nucleo-F302R8. I've followed the user manual UM1964 to setting up the example both in the standalone version and in the UART version.

Thanks,

Francesco

**Comment by cparata** [comment]
Hi @FraGiura ,
I checked the schematics and with Nucleo-F302R8 you need a small hardware fix on the shield. In particular on Nucleo-F302R8 in D3 (PB3) we do not have the SPI2 clock. So you are obliged to use D13 instead D3 as SPI2 clock. In order to do that you need to unsolder SB34 and solder SB12 on X-NUCLEO-IHM02A1 and then initialize the SPI instance in the sketch in this way:

dev_spi = new SPIClass(D11, D12, D13);

I hope that this tip can help you to solve your issue.
Best Regards,
Carlo

**Comment by FraGiura** [comment]
Hi Carlo (@cparata ),
thanks to your suggestion I finally figure out the problem.

The problem was in the SPI pins and I want add something that could be helpful for who has a problem like this.

There is a problem in the X-NUCLEO-IHM02A1 documentation:
In the documentation (UM1964-User manual-DocID028481-Rev 1- pag. 15/24):

SB10 >> PB15 as L6470_1_SDI
SB26 >> PA7  as L6470_1_SDI  

SB32 >> PA6  as L6470_0_SD0
SB11 >> PB14 as L6470_0_SD0

SB34 >> PB3  as  L64701_SCK/L64702_SCK
SB12 >> PA5  as  L64701_SCK/L64702_SCK
SB13 >> PB13 as  L64701_SCK/L64702_SCK

The real connection is:

SB10 >> **PA7** as L6470_1_SDI
SB26 >> **PB15**  as L6470_1_SDI  

SB32 >> **PB14**  as L6470_0_SD0
SB11 >> **PA6**  as L6470_0_SD0

SB34 >> PB3 as  L64701_SCK/L64702_SCK
SB12 >> **PB13**  as  L64701_SCK/L64702_SCK
SB13 >> **PA5** as  L64701_SCK/L64702_SCK

The example X-CUBE-SPN2 set SPI2 at this pins:

    /**SPI2 GPIO Configuration    
    PB13     ------> SPI2_SCK
    PB14     ------> SPI2_MISO
    PB15     ------> SPI2_MOSI

So I finally use SB26, SB32, SB12 and everything works.

Many thanks to  @cparata for his help.

Best regards,
Francesco
