### ISSUE TITLE
Issue to start 2 stepper motors at the same time

### ISSUE THREAD

**Issue by alcocerg** [stm32duino/X-NUCLEO-IHM02A1#3]
Hello,
I'm using the following commands that are available in the X_NUCLEO_IHM02A1_HelloWorld.ino:
                motors[0]->PrepareRun(StepperMotor::BWD, 200);
                motors[1]->PrepareRun(StepperMotor::FWD, 200);
                x_nucleo_ihm02a1->PerformPreparedActions(); }
I see the stepper motor connected on motors[0] starting immediatly and at full speed. The stepper motor connected on motors[1] starts with a visible delay and takes more time to reach the full speed.
Inverting the 2 stepper motors swap the problem.
I have exactly the same behavior when using the HelloWorld_IHM02A1 in mbed.
I'm using a NucleoL476RG.
So, the IHM02A1 doesn't seem to be capable to start 2 stepper motors at the same time despite the dedicated set of commands.
Do you confirm this wrong behavior ?

regards,
Gilles Alcocer
STM32 ODE MKT

**Comment by cparata** [comment]
Hi Gilles,
could you post the entire sketch that you are using?
Thank you and Best Regards,
Carlo

**Comment by alcocerg** [comment]
Hi Carlo,
sketch attached.
Regards,
Gilles
[X_NUCLEO_IHM02A1_HelloWorld.zip](https://github.com/stm32duino/X-NUCLEO-IHM02A1/files/1841557/X_NUCLEO_IHM02A1_HelloWorld.zip)

**Comment by davidroid** [comment]
Hello Gilles,
thank you for signaling. We have verified the issue at our side too. Please let us better debug in the coming days.

Cheers,
Davide

**Comment by cparata** [comment]
I can close this issue because it was solved by this fix: https://github.com/stm32duino/X-NUCLEO-IHM02A1/pull/4

**Comment by cparata** [comment]
Hi Gilles,
I did more tests and I noticed that Nucleo-F302R8 is not hardware compatible with X-NUCLEO-IHM02A1 by default. In order to be compatible we need to move the SPI clock from D3 (default pin) to D13 on X-NUCLEO-IHM02A1. In fact the Nucleo-F302R8 has in D3 the SPI clock of SPI3, in D12 the SPI MISO of SPI2, in D11 the SPI MOSI of SPI2 and in D13 the SPI clock of SPI2. So in order to use the correct SPI peripheral we need to use D13 as clock instead D3 and change accordingly the sketch. With Nucleo-L476RG instead we should have the same behavior of Nucleo-F401RE or Nucleo-F411RE. So, it is very strange that you have issues with L4.
Best Regards,
Carlo
