### ISSUE TITLE
Question: How to implement more than one expansion board (3+ motors)?

### ISSUE THREAD

**Issue by adamaero** [stm32duino/X-NUCLEO-IHM02A1#9]
Looking at the .cpp file, there this:
`uint8_t XNucleoIHM02A1::number_of_boards = 0;`

Does each "ACTION" in the .cpp file need to have an addition? And does a new initializer need to be created in the .ino file?

(I don't know how to assign this the question label.)

**Comment by cparata** [comment]
Hi @adamaero ,
I have never tried to stack more than one IHM02A1 board, so I'm not sure that the configuration that you are trying is supported by current library. Anyway, you should assign a different Chip Select at each expansion board soldering SB23 or SB7 or SB8 or SB9 (so for example in the first IHM02A1 you can leave SB23 closed and in the second one you need to unsolder SB23 and solder SB7). After that you can try to initialize 2 instances of IHM02A1 passing the same SPI Clock, MOSI and MISO pins and changing only the SSEL pin (A2 for the first one and D2 for the second one) and then see if you are able to control the 3 motors. Let me know if it works because I'm interested in this test.
Best Regards,
Carlo

**Comment by cparata** [comment]
I forgot to mention that obviously you also need the patch for the SPI Clock also for the second IHM02A1 like you did in the previous Issue that you opened.

**Comment by adamaero** [comment]
Yes, I switched that right away. I'll test the second board soon.

**Comment by adamaero** [comment]
It just stopped working all together. From previously, SB12 is soldered (instead of SB34) on both expansion boards. Like the data sheet said, I unsoldered SB23 and soldered SB7.
These are the changes made to the example file:
```
    XNucleoIHM02A1 *x_nucleo_ihm02a1;
    XNucleoIHM02A1 *x_nucleo_ihm02a1two;

    /* Initializing Motor Control Expansion Board. */
    x_nucleo_ihm02a1 = new XNucleoIHM02A1(&L6470_init[0], &L6470_init[1], A4, A5, D4, A2, dev_spi);
    x_nucleo_ihm02a1two = new XNucleoIHM02A1(&L6470_init[0], &L6470_init[1], A4, A5, D4, D2, dev_spi);  // @@ new: D2

    /* Building a list of motor control components. */
    motors = x_nucleo_ihm02a1->get_components();
    motors = x_nucleo_ihm02a1two->get_components();         // @@ new

```

**Comment by cparata** [comment]
Hi @adamaero ,
could you share the entire sketch? I noticed that you are using the same pointer for the 2 shields. You need to define two different pointers.
Best Regards,
Carlo

**Comment by fpistm** [comment]
@cparata, it is not exactly the same as A2 replaced by D2.
So, SSEL is different.

**Comment by cparata** [comment]
Hi @fpistm ,
yes I just referred to "motors" pointer that should be split as "motors" and "motorstwo".
Best Regards,
Carlo

**Comment by fpistm** [comment]
Ah right. Sorry my mistake 🙄

**Comment by adamaero** [comment]
A mistake, I think, fixed:
`    x_nucleo_ihm02a1two = new XNucleoIHM02A1(&L6470_init[0], &L6470_init[1], A4, D2, D4, A2, dev_spi);
`

From the .h:
![image](https://user-images.githubusercontent.com/26505046/62138767-d12d3d00-b2ad-11e9-9dc9-4a3352840663.png)

Unrelated, I set the Serial Monitor to 115200 baud...no output...ever.

**Comment by adamaero** [comment]
I'll try to update my fork in sync to what I'm doing:

https://github.com/adamaero/X-NUCLEO-IHM02A1/blob/master/examples/X_NUCLEO_IHM02A1_HelloWorld/X_NUCLEO_IHM02A1_HelloWorld.ino

He says I don't need to make any changes: https://stackoverflow.com/a/57260684/2829176

**Comment by cparata** [comment]
Hi @adamaero ,
unfortunately I do not have another shield to test your setup. Another possibility is to use another SPI instance of the F747 board wiring the connection to the second shield. Have you ever tried this configuration?
Best Regards,
Carlo

**Comment by adamaero** [comment]
It's getting closer: https://stackoverflow.com/questions/57434935/compiles-and-motor-driver-shields-work-individually-but-not-together

I haven't tried making a second SPI configuration. Still trying to do it with one, can the second instance have the same "A4, A5, D4" pins?

```
x_nucleo_ihm02a1 =    new XNucleoIHM02A1(&init[0], &init[1], A4, A5, D4, D2, &dev_spi);
x_nucleo_ihm02a1two = new XNucleoIHM02A1(&init[0], &init[1], A4, A5, D4, A2, &dev_spi);
```

Do the interrupts and flags need to be different?

**Comment by fpistm** [comment]
@adamaero, @cparata 
any update on this ?

**Comment by adamaero** [comment]
@fpistm Nope. I never got it to work with three or more, asynchronous.

**Comment by cparata** [comment]
Hi @adamaero ,
did you try using as second SPI for example PC12 as MOSI, PC11 as MISO, PC10 as Clock?
Obviously, in that way you should control the motors independently and not in daisy chain.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @adamaero ,
do you have any update about the test that I proposed?
Best Regards,
Carlo

**Comment by adamaero** [comment]
My internship ended. 
I tried everything that was suggested before September 2019.

**Comment by fpistm** [comment]
Thanks  @adamaero for feedback.

**Comment by Adrien9o2** [comment]
Hello,
I was able to stack and use more than one xnucleoIHM02A1, by modifying the provided arduino library.
I imported that library in STM32cubeIDE and replaced the spi communication functions with HAL functions but the fix i used should work on the arduino library too.

You can find the modified library here :
https://github.com/Adrien9o2/stm32_to_ros
 
The readme explains the step i took in order to have the correct solder bridge configuration and avoid pin conflicts.

The main fix i needed is to add a template to the L6470 class, so that static variables are only shared among L6470 of the same shield/board. 

I also made some modifications for myself such as removing mentions of flag/busy pin since i do not needed it.
